### ISSUE TITLE
Respect the config file

### ISSUE THREAD

**Issue by kalkin** [guard/guard-brakeman#29]
First of all thanks for the fine work. :+1: 

I have a simple config file (`config/brakeman.yml`) which contains the following:

``` yaml

---
:run_all_checks: true
```

When i run directly `brakeman` it works flawlessly, but guard seems to ignore it.
According to the `README` this paths should be tried for finding the config.

> The default config locations are ./config/brakeman.yml, ~/.brakeman/config.yml, and /etc/brakeman/config.yml

**Comment by e2** [comment]
Looks like `Guard::Brakeman` just doesn't look for config files. 

Probably because people may want a different config when running with guard. (Normally, plugin options are in the Guardfile).

Here's a quick "hack" in your `Guardfile` to fix this.

```ruby

configs = %w(./config/brakeman.yml ~/.brakeman/config.yml /etc/brakeman/config.yml)
defaults = configs.detect { |f| break YAML.load(IO.read(File.expand_path(f))) rescue Errno::ENOENT; nil } || {}
my_options = defaults # or e.g. defaults.merge(notifications: false)

guard 'brakeman', my_options do
  watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
  watch(%r{^config/.+\.rb$})
  watch(%r{^lib/.+\.rb$})
  watch('Gemfile')
end
```

@oreoshake - what do you think of putting this into the Guardfile template?

**Comment by oreoshake** [comment]
@e2 I'd rather figure out why it isn't picking the config file up by default. I haven't touched this code in years so I don't know off the top of my head :disappointed: 

I can probably look at this later this week unless someone beats me to it :+1: 

I'm assuming this was always broken but I think there were recent changes to how brakeman handles this @presidentbeef.

**Comment by e2** [comment]
@oreoshake - you're right. It looks like it should work: 

`set_config` is called here:

https://github.com/guard/guard-brakeman/blob/master/lib/guard/brakeman.rb#L51

and it should load the config, as here:

https://github.com/presidentbeef/brakeman/blob/497a5483abf5ea32634184c73c4010f9a1cff737/lib/brakeman.rb#L76

So something seems wrong.


@kalkin - could you set the debug mode by editing the gem's code and changing this line:

https://github.com/guard/guard-brakeman/blob/master/lib/guard/brakeman.rb#L51

to:

```ruby
@scanner_opts = ::Brakeman::set_options({:app_path => '.', :quiet => true}.merge(@options))
```

and then paste the output? 

We should then be able to see what's going on. Thanks!

**Comment by kalkin** [comment]
@e2 I did that. But AFAIK i do not see more output as before when i.e. removing `quiet: true`
```
[1] guard(main)> 
11:54:07 - INFO - Run all
 - CheckBasicAuth
 - CheckCrossSiteScripting
 - CheckContentTag
 - CheckCreateWith
 - CheckDefaultRoutes
 - CheckDeserialize
 - CheckDetailedExceptions
 - CheckDigestDoS
 - CheckEscapeFunction
 - CheckEvaluation
 - CheckExecute
 - CheckFileAccess
 - CheckFileDisclosure
 - CheckFilterSkipping
 - CheckForgerySetting
 - CheckHeaderDoS
 - CheckI18nXSS
 - CheckJRubyXML
 - CheckJSONEncoding
 - CheckJSONParsing
 - CheckLinkTo
 - CheckLinkToHref
 - CheckMailTo
 - CheckMassAssignment
 - CheckModelAttrAccessible
 - CheckModelAttributes
 - CheckModelSerialize
 - CheckNestedAttributes
 - CheckNumberToCurrency
 - CheckQuoteTableName
 - CheckRedirect
 - CheckRegexDoS
 - CheckRender
 - CheckRenderDoS
 - CheckRenderInline
 - CheckResponseSplitting
 - CheckSafeBufferManipulation
 - CheckSanitizeMethods
 - CheckSelectTag
 - CheckSelectVulnerability
 - CheckSend
 - CheckSendFile
 - CheckSessionManipulation
 - CheckSessionSettings
 - CheckSimpleFormat
 - CheckSingleQuotes
 - CheckSkipBeforeFilter
 - CheckSQL
 - CheckSQLCVEs
 - CheckSSLVerify
 - CheckStripTags
 - CheckSymbolDoSCVE
 - CheckTranslateBug
 - CheckUnsafeReflection
 - CheckValidationRegex
 - CheckWithoutProtection
 - CheckXMLDoS
 - CheckYAMLParsing
 - CheckSymbolDoS
 - CheckUnscopedFind
 - CheckWeakHash
Checks finished, collecting results...
11:54:07 - INFO - 
> [#516753F71B4D] ------ brakeman warnings --------
> [#516753F71B4D] 
11:54:07 - INFO - 0 brakeman findings
```

**Comment by e2** [comment]
Actually, just adding quiet as a guard option should work:

```ruby
guard 'brakeman', :run_on_start => true, :quiet => false do
  watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
  watch(%r{^config/.+\.rb$})
  watch(%r{^lib/.+\.rb$})
  watch('Gemfile')
end
```

and it should say: `[Notice] Using configuration (...)`

**Comment by e2** [comment]
I made a mistake earlier about `quiet: true`, because that actually silences the errors.

**Comment by kalkin** [comment]
Ok adding `quiet: false` shows:
```
[Notice] Using configuration in /home/user/moeb/config/brakeman.yml
```

This sounds right, but even if my config file has `:run_all_cheks: true` not all checks are run. Brakeman, run by guard, does not yield the same results as `brakeman -A`

**Comment by kalkin** [comment]
Also it should probably watch the `config/brakeman.yml` for changes. At the momment it watches just the `config/*.rb` files

**Comment by e2** [comment]
@kalkin - I couldn't find a difference (except for the report not being shown). Which checks weren't run? Are you using additional checks?

The following config should make the config almost exactly the same as running Brakeman manually:

```ruby
options = {
  :run_on_start => true,
  :quiet => false,
  :chatty => true,
  :min_confidence=>2,
  :print_report=>true
}

guard 'brakeman', options do
  watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
  watch(%r{^config/.+\.rb$})
  watch(%r{^lib/.+\.rb$})
  watch('Gemfile')
end
```

**Comment by kalkin** [comment]
@e2 Thanks for the reply. When i hardcoded the options like you suggested, brakeman has one finding:
```
[Notice] Using configuration in /home/user/FOO/config/brakeman.yml
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...sed
Processing routes...          
Processing templates...       
Processing data flow in templates...
Processing models...          
Processing controllers...     
Processing data flow in controllers...
Indexing call sites...        
 - CheckBasicAuth
 ..... A LOT OF CHECKS ....
 - CheckWeakHash
Checks finished, collecting results...
13:56:06 - INFO - 
> [#877683294408] ------ brakeman warnings --------
> [#877683294408] 
13:56:06 - INFO - 1 brakeman findings
13:56:06 - INFO - ["Weak", :white] - Unscoped Find - Unscoped call to Donation#find near line 15 in /home/user/FOO/app/controllers/donations_controllerrb: Donation.find(params[:id])
```

This is the supposed behaviour.

I experimented a little bit and noticed this works as good as your proposal:
```ruby
guard 'brakeman', min_confidence: 2, run_on_start: true do
   watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
   watch(%r{^config/.+\.rb$})
   watch(%r{^lib/.+\.rb$})
   watch('Gemfile')
 end
```

**Comment by e2** [comment]
Lazy patch here: https://github.com/guard/guard-brakeman/pull/30

**Comment by kalkin** [comment]
Old can be closed
